services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./workflows:/home/node/workflows
      - ./local-files:/files
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_SKIP_AUTH_ON_OAUTH_CALLBACK=true
      - N8N_RESTRICT_FILE_ACCESS_TO=/files
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    command: http n8n:5678
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    restart: unless-stopped